apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: logstash
  template:
    metadata:
      labels:
        k8s-app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:7.3.2
          volumeMounts:
          - mountPath: /logs
            name: vol1
          - mountPath: /usr/share/logstash/pipeline/logstash.conf
            name: vol2
          - mountPath: /usr/share/logstash/config/logstash.yml
            name: vol3
      volumes:
      - hostPath:
          path: /docker/mss/logs
        name: vol1
      - hostPath:
          path: /docker/logstash/logstash.conf
        name: vol2
      - hostPath:
          path: /docker/logstash/logstash.yml
        name: vol3
