apiVersion: apps/v1
kind: Deployment
metadata:
  name: mss-static
  namespace: mss
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mss-static
  template:
    metadata:
      labels:
        k8s-app: mss-static
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /dist
            name: vol1
          - mountPath: /etc/nginx/conf.d
            name: vol2
          - mountPath: /var/log/nginx
            name: vol3
      volumes:
      - hostPath:
          path: /docker/nginx/dist
          type: DirectoryOrCreate
        name: vol1
      - hostPath:
          path: /docker/nginx/conf
          type: DirectoryOrCreate
        name: vol2
      - hostPath:
          path: /docker/nginx/log
          type: DirectoryOrCreate
        name: vol3
---
apiVersion: v1
kind: Service
metadata:
  name: mss-static-external
  namespace: mss
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 81
  type: NodePort
  selector:
    k8s-app: mss-static
