apiVersion: apps/v1
kind: Deployment
metadata:
  name: mss-config
  namespace: mss
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mss-config
  template:
    metadata:
      labels:
        k8s-app: mss-config
    spec:
      containers:
        - name: mss-config
          image: 192.168.100.49:5000/mss-config
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mss-config-external
  namespace: mss
spec:
  ports:
    - port: 8010
      targetPort: 8010
      protocol: TCP
      nodePort: 8010
  type: NodePort
  selector:
    k8s-app: mss-config
