apiVersion: apps/v1
kind: Deployment
metadata:
  name: mss-static
  namespace: mss
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mss-static
  template:
    metadata:
      labels:
        k8s-app: mss-static
    spec:
      containers:
        - name: nginx
          image: nginx:1.16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /docker/nginx/data
            name: vol1
          - mountPath: /docker/nginx/conf
            name: vol2
      volumes:
      - hostPath:
          path: /data
          type: DirectoryOrCreate
        name: vol1
      - hostPath:
          path: /etc/nginx/conf.d
          type: DirectoryOrCreate
        name: vol2
---
apiVersion: v1
kind: Service
metadata:
  name: mss-static-external
  namespace: mss
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    k8s-app: mss-static
